# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://kawishqayyum.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Syed Kawish Qayyum"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Kawish Qayyum
author-bio: Python Developer # change to false to hide
author-image: kawish.jpg # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
  - text: About
    permalink: about
  - text: Blog
    permalink: blog

# use false to turn off any social media links
linkedin: https://linkedin.com/in/kawishqayyum
twitter: https://twitter.com/kawishqayyum
facebook: false
instagram: false
github: https://github.com/kawishqayyum
medium: https://medium.com/@kawishqayyum
google-scholar: false
email: mailto:kawishqayyum@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
  - jekyll-seo-tag
